### PR TITLE
microsoft.workloadiam: Refactor subcommand invocation

### PR DESCRIPTION
**Pull request by AntonioND**
The old code was unreliable. The new code should work in a similar way but it should be able to handle errors in a more graceful way.

For example, this is the output in a successful run:
ok

And this is the output in a non-successful run when the user has already used that local authority before and the workload-iam extension fails to create a join token:
not ok

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by dafang982** [comment]
It would be nice to provide what manual tests have been done and what the output looks like.

**Review by dafang982 — APPROVED** [review]
LGTM. Please write in the description what manual tests were done.

**Comment by AntonioND** [comment]
> LGTM. Please write in the description what manual tests were done.

I've updated the description.

**Comment by AntonioND** [comment]
I'm closing this PR as I've opened one in the upstream repository: https://github.com/AzureArcForKubernetes/azure-cli-extensions/pull/267

**Pull request closed without merging**
